import CircularDependencyPlugin from "circular-dependency-plugin";
import HtmlWebpackPlugin from "html-webpack-plugin";
import webpack from "webpack";

import webpackBaseBabel from "./webpack.base.babel.js";

export default webpackBaseBabel({
  mode: "development",

  // Don't use hashes in dev mode for a better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },

  devServer: {
    contentBase: ["./app"],
    inline: true,
    hot: true,
  },

  optimization: {
    splitChunks: {
      chunks: "all",
    },
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "app/index.html",
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",

  performance: {
    hints: false,
  },
});
