/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

import CircularDependencyPlugin from "circular-dependency-plugin";
import HtmlWebpackPlugin from "html-webpack-plugin";
import path from "path";
import webpack from "webpack";

import webpackBaseBabel from "./webpack.base.babel.js";

export default webpackBaseBabel({
  mode: "development",

  // Add hot reloading in development
  // entry: [
  //   "webpack-hot-middleware/client?reload=true",
  //   path.join(process.cwd(), "app/app.js"), // Start with js/app.js
  // ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },

  devServer: {
    contentBase: ["./app"],
    inline: true,
    hot: true,
  },

  optimization: {
    splitChunks: {
      chunks: "all",
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "app/index.ejs",
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",

  performance: {
    hints: false,
  },
});
